### ISSUE TITLE
简化方案

### ISSUE THREAD

**Issue by kagayatsuki** [ZJ595/Drcom#1]
在15栋宿舍楼实测密码明文传递即可，并且可以再简化
datas = 'DDDDD={}&upass={}&v46s=0&v6ip=&f4serip=172.17.2.252&0MKKey='

headers可以如此简化
headers={
    'Host': '172.17.2.252',
    'Connection': 'keep-alive',
    'Content-Length': '{}'.format(len(datas)),
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
}，其中Content-Length的值格式化为data的长度

另外一提，requests似乎并非python自带库，需要通过pip install来安装才能使用脚本

然后脚本差不多长这个样子：

import requests
import base64
import time

with open("pass.txt", "r") as f:
    data = f.read().split('&')
    username = data[0]  #获取学号
    b = data[1]
    password = b

time.sleep(5)  #设置延迟，避免有时候可能还没连上wifi而出错

datas='DDDDD={}&upass={}&0MKKey=&v6ip='.format(username,password)

headers={
    'Host': '172.17.2.252',
    'Connection': 'keep-alive',
    'Content-Length': '{}'.format(len(datas)),
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
}

url = 'http://172.17.2.252/'
r = requests.post(url=url,data=datas,headers=headers).text #发送联网请求

**Comment by ZJ595** [comment]
可以啊好兄弟，我在2栋测试密码要密文，requests确实是非标准库，但是给其他同学用的都是打包好的exe文件，会看py代码的，基本上都是会安装第三方库的，所以就没考虑到这里。hearders也可以再简化，我习惯都是fd抓包，然后直接复制粘贴。
居然还会有人给我提issues，这是我没想到的，加个联系方式好兄弟？

**Comment by kagayatsuki** [comment]
好呀，已经加你QQ了

**Comment by lightdev-top** [comment]
草ww🤣我也滇池学院

**Comment by lightdev-top** [comment]
![image](https://user-images.githubusercontent.com/56513857/134672527-d4a03491-dafb-43e9-a15a-998061b4c840.png)
自己也写了个

**Comment by lightdev-top** [comment]
![无标题](https://user-images.githubusercontent.com/56513857/134672941-82e7121c-c5e2-4979-ba94-75afcfcb18fa.png)
自己也写了个

**Comment by ZJ595** [comment]
> 草ww🤣我也滇池学院

好家伙，又有同道中人，加个联系方式？

**Comment by lightdev-top** [comment]
> > 草ww🤣我也滇池学院
> 
> 好家伙，又有同道中人，加个联系方式？

Q2505052829

**Comment by Thomas-little-train** [comment]
请问大佬可以在路由器里面跑吗，我也是滇院 最近一直在搞这个路由器

**Comment by kagayatsuki** [comment]
你的路由器作为交换机使用的，所以能跑也没用

**Comment by ZJ595** [comment]
> 大佬可以在外面跑吗，我也是滇院最近一直在搞这个主机

自己刷个路由器吧，想要啥功能都可以自己定制

**Comment by Thomas-little-train** [comment]
可以加一下联系方式吗 大佬

**Comment by ZJ595** [comment]
> 可以加一下联系方式吗

q1411632412
